(()=>{
 const $=s=>document.querySelector(s);
 const query=$('#answer-filter');if(query){const rows=[...document.querySelectorAll('.answer-library .answer')];const run=()=>{const q=query.value.trim().toLowerCase();let count=0;rows.forEach(r=>{r.hidden=!r.textContent.toLowerCase().includes(q);if(!r.hidden)count++});$('#answer-count').textContent=count+' answer'+(count===1?'':'s');$('#answer-empty').hidden=count>0};query.addEventListener('input',run);run()}
 const data=$('#tuition-data');if(data){const rates=JSON.parse(data.textContent),attendance=$('#tuition-attendance'),payment=$('#tuition-payment');const update=()=>{const p=rates[attendance.value],i=Number(payment.value),cost=p.rates[i],periods=[12,4,1][i],fmt=x=>'$'+x.toLocaleString('en-US');$('#tuition-name').textContent=p.name;$('#tuition-amount').textContent=fmt(cost);$('#tuition-frequency').textContent='per '+['month','quarter','year'][i];$('#tuition-total').textContent=fmt(cost*periods)+' full-year tuition · '+periods+' payment'+(periods===1?'':'s')};attendance.addEventListener('change',update);payment.addEventListener('change',update);update()}
 const switchTab=b=>{const list=b.closest('[role=tablist]');list.querySelectorAll('[role=tab]').forEach(t=>{const active=t===b;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!active})};
 document.querySelectorAll('.explorer-tabs [role=tab]').forEach(b=>{b.addEventListener('click',()=>switchTab(b));b.addEventListener('keydown',e=>{const all=[...b.parentElement.children];let i=all.indexOf(b);if(e.key==='ArrowRight')i=(i+1)%all.length;else if(e.key==='ArrowLeft')i=(i+all.length-1)%all.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=all.length-1;else return;e.preventDefault();switchTab(all[i]);all[i].focus()})});
 // Keep wide data inside its own scroll region on phones.
 document.querySelectorAll('.source-content table,.reading-width table').forEach(t=>{if(!t.parentElement.classList.contains('data-scroll')&&!t.closest('.schedule-table-wrap')){const wrap=document.createElement('div');wrap.className='data-scroll';t.before(wrap);wrap.append(t)}});
 document.querySelectorAll('iframe').forEach(f=>{if(!f.title)f.title='River Tech video';if(!f.loading)f.loading='lazy'});
})();
(()=>{const buttons=[...document.querySelectorAll('[data-week-day]')],result=document.querySelector('#week-result');if(!result)return;buttons.forEach(b=>b.addEventListener('click',()=>{const selected=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(selected));b.querySelector('b').textContent=selected?'✓':'+';const days=buttons.filter(x=>x.getAttribute('aria-pressed')==='true');result.replaceChildren();if(!days.length){result.textContent='Select one or more days above.';return}const price=document.createElement('strong');price.textContent='$'+[0,365,690,960,1199][days.length].toLocaleString('en-US')+' / quarter';const description=document.createElement('p');description.textContent=days.length+'-day homeschool plan · Per student';result.append(price,description);days.forEach(d=>{const a=document.createElement('a');a.href=d.dataset.weekLink;a.textContent=d.dataset.weekDay+': '+d.dataset.weekTitle+' ↗';result.append(a)});const note=document.createElement('small');note.textContent='Tuition only. Fees and sibling discounts are on the tuition page. Openings are filled from the free wait pool.';result.append(note)}))})();
